swagger: '2.0'
info:
  title: Deep Space API
  version: 1.0.0
basePath: https://client.deepspacesync.com/api/v1/
schemes:
- https
securityDefinitions:
  JWT:
    authorizationUrl: ''
    flow: implicit
    type: oauth2
paths:
  /login:
    post:
      summary: Login to get JWT token
      description: Validates Deep Space username and password and returns JWT token
        for API
      operationId: login
      tags:
      - Authentication
      parameters:
      - name: username
        in: header
        required: true
        type: string
      - name: password
        in: header
        required: true
        type: string
      responses:
        200:
          description: JWT
          schema:
            type: string
        401:
          description: Unauthorized
        500:
          description: Internal Server Error
  /workspaces:
    get:
      summary: Get list of workspaces and associated projects
      description: Returns all workspaces and projects a user has access to with optional
        parameter to specify access permissions
      operationId: getWorkspaces
      tags:
      - Workspaces
      parameters:
      - name: permissions
        in: query
        required: false
        type: string
        enum:
        - isProjectManager
        - isProjectViewer
        - isRevitUser
      security:
      - JWT: []
      responses:
        200:
          description: Successful response with a list of workspaces and projects
          schema:
            type: array
            items:
              type: object
              properties:
                workspace:
                  description: ds_workspace_name corresponding to dataset name
                  type: string
                  example: ds_12345678_9123_4567_8912_123456789123
                workspace_name:
                  type: string
                  example: My Workspace Name
                projects:
                  type: array
                  items:
                    type: object
                    properties:
                      project_id:
                        type: integer
                        example: 1
                      project_name:
                        type: string
                        example: My Project Name
        401:
          description: Unauthorized
        400:
          description: Bad Request due to invalid parameters
        204:
          description: No content to return
        500:
          description: Internal Server Error
  /workspaces/{workspaceId}/projects/{projectId}/sourcefiles:
    get:
      summary: Get sourcefies by projectid
      description: Returns all sourcefiles details for a project
      operationId: getSourceFiles
      tags:
      - Files
      parameters:
      - name: workspaceId
        in: path
        required: true
        type: string
      - name: projectId
        in: path
        required: true
        type: integer
      security:
      - JWT: []
      responses:
        200:
          description: A list of sourcefiles
        401:
          description: Unauthorized
        500:
          description: Internal Server Error
    post:
      summary: Create a sourcefile in a project
      description: Creates a new sourcefile in a project with provided filename and
        discipline
      operationId: postSourceFiles
      tags:
      - Files
      consumes:
      - application/json
      parameters:
      - name: workspaceId
        in: path
        required: true
        type: string
      - name: projectId
        in: path
        required: true
        type: integer
      - name: body
        in: body
        required: true
        schema:
          type: object
          required:
          - filename
          - discipline
          properties:
            filename:
              type: string
              description: The name of the sourcefile
            discipline:
              type: string
              description: The discipline of the sourcefile
      security:
      - JWT: []
      responses:
        201:
          description: Sourcefile successfully created
          schema:
            description: idSourceFiles
            type: string
        401:
          description: Unauthorized
        409:
          description: Filename already exists
        400:
          description: Bad Request
        500:
          description: Internal Server Error
  /workspaces/{workspaceId}/projects/{projectId}/data/any:
    post:
      summary: Upload any data to Deep Space
      description: Generic endpoint to upload csv data in any format to Deep Space
        in EAV format.
      operationId: uploadanydata
      tags:
      - Upload Data
      consumes:
      - multipart/form-data
      parameters:
      - name: workspaceId
        in: path
        required: true
        type: string
      - name: projectId
        in: path
        required: true
        type: integer
      - name: file
        in: formData
        required: true
        type: string
        description: The CSV file to upload
      - name: data_classification
        in: formData
        required: true
        type: string
        description: The unique identifying name to categorise the data type
      security:
      - JWT: []
      responses:
        200:
          description: ingest_id of successfully loaded data
          schema:
            type: string
        401:
          description: Unauthorized
        500:
          description: Internal Server Error
  /workspaces/{workspaceId}/projects/{projectId}/data:
    get:
      summary: Get list of data classifications
      operationId: getDataClassifications
      tags:
      - Upload Data
      parameters:
      - name: workspaceId
        in: path
        required: true
        type: string
      - name: projectId
        in: path
        required: true
        type: integer
      security:
      - JWT: []
      responses:
        200:
          description: A list of supported data classifications
        401:
          description: Unauthorized
        500:
          description: Internal Server Error
  /workspaces/{workspaceId}/projects/{projectId}/data/{data_classification}:
    get:
      summary: Get list of data sources
      operationId: getDataSources
      tags:
      - Upload Data
      parameters:
      - name: workspaceId
        in: path
        required: true
        type: string
      - name: projectId
        in: path
        required: true
        type: integer
      - name: data_classification
        in: path
        required: true
        type: string
        description: The classification of the data
      security:
      - JWT: []
      responses:
        200:
          description: A list of supported data sources
        401:
          description: Unauthorized
        500:
          description: Internal Server Error
        400:
          description: Bad Request
  /workspaces/{workspaceId}/projects/{projectId}/data/{data_classification}/{data_source}/{export_type}/{export_version}:
    post:
      summary: Upload data to Deep Space from supported formats
      operationId: uploaddata
      tags:
      - Upload Data
      consumes:
      - multipart/form-data
      parameters:
      - name: workspaceId
        in: path
        required: true
        type: string
      - name: projectId
        in: path
        required: true
        type: integer
      - name: data_classification
        in: path
        required: true
        type: string
        description: The classification of the data
      - name: data_source
        in: path
        required: true
        type: string
        description: The source of the data
      - name: export_type
        in: path
        required: true
        type: string
        description: The type of export
      - name: export_version
        in: path
        required: true
        type: string
        description: The version of the export
      - name: file
        in: formData
        required: true
        type: string
        description: The file to upload
      security:
      - JWT: []
      responses:
        200:
          description: crawlId of successfully loaded data
          schema:
            type: string
        401:
          description: Unauthorized
        500:
          description: Internal Server Error
        400:
          description: Bad Request
        422:
          description: Unprocessable Entity
  /workspaces/{workspaceId}/projects/{projectId}/parameters:
    get:
      summary: Get parameters for project
      description: Get list of unique parameters from all parameter sets for a project
      operationId: getParameters
      tags:
      - Parameters
      parameters:
      - name: workspaceId
        in: path
        required: true
        type: string
      - name: projectId
        in: path
        required: true
        type: integer
      security:
      - JWT: []
      responses:
        200:
          description: A list of parameters
        401:
          description: Unauthorized
        500:
          description: Internal Server Error
